window.today={
title:"今日测试",
questions:[
{
type:"choice",
question:"HPLC中用于推动流动相通过色谱柱的是？",
options:["检测器","泵","进样器","色谱柱"],
answer:1,
explanation:"泵提供压力推动流动相。"
},
{
type:"choice",
question:"药代动力学中的ADME分别代表？",
options:["吸收分布代谢排泄","分析检测测量实验","抗原蛋白免疫反应","无"],
answer:0,
explanation:"ADME是吸收、分布、代谢和排泄。"
}
]
};